name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: LimeStudio

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android/setup-android@v2
        with:
          sdk-platform: '30'

      - name: Build and test
        run: |
          chmod +x gradlew
          ./gradlew build
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

      - name: Archive APKs
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk  # Update the path

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Create or Update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.download.outputs.artifact-path }}/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}